import Head from "next/head";
import Link from "next/link";
import React from "react";
import { projects } from "../data";

const Projects = () => {
  // console.log(projects[0].image.default);
  return (
    <>
      <Head>
        <title>Projects | Nguyen Vu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <section className="projects">
          <h1 className="base__title">Projects</h1>
          <div className="projects__container">
            {projects.map((project) => (
              <article
                key={project.id}
                className="project"
                style={{
                  backgroundImage: `url(${project.image.default.src})`,
                }}
              >
                <Link href={`/projectDetail/${project.id}`} className="project__linkContainer">
                  <div className="project__container">
                    <h3 className="project__name">
                      {project.name}
                      <span>_</span>
                    </h3>
                  </div>
                </Link>
              </article>
            ))}
          </div>
          {/* <div className="base__seeMore">
            <a href="">See More</a>
          </div>
          <div className="btnChangePerspective">
            <button type="button" name="button">
              <span>3D Mode</span>
            </button>
          </div> */}
        </section>
      </div>
    </>
  );
};

export default Projects;
