import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import { projects } from "../data";

const Projects = () => {
  const [data, setData] = useState(projects);
  const [category, setCategory] = useState("all");
  useEffect(() => {
    setData(data);
  }, [data]);

  const handleFilter = (category) => {
    const dataFilters = projects.filter((p) => p.category === category);
    setData(dataFilters);
    setCategory(category);
  };

  return (
    <>
      <Head>
        <title>Projects | Nguyen Vu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <section className="projects">
          <header className="projects__header">
            <h1 className="base__title">Projects</h1>
            <div className="projects__filters">
              <div
                className="btnChangePerspective"
                onClick={() => handleFilter("fe")}
              >
                <button
                  type="button"
                  name="button"
                  className={category === "fe" ? "active" : ""}
                >
                  <span>Frontend</span>
                </button>
              </div>

              <div
                className="btnChangePerspective"
                onClick={() => handleFilter("be")}
              >
                <button
                  type="button"
                  name="button"
                  className={category === "be" ? "active" : ""}
                >
                  <span>Backend</span>
                </button>
              </div>
              <div
                className="btnChangePerspective"
                onClick={() => handleFilter("bc")}
              >
                <button
                  type="button"
                  name="button"
                  className={category === "bc" ? "active" : ""}
                >
                  <span>Blockchain</span>
                </button>
              </div>
              <div className="btnChangePerspective">
                <button
                  className={category === "all" ? "active" : ""}
                  type="button"
                  name="button"
                  onClick={() => {
                    setData(projects);
                    setCategory("all");
                  }}
                >
                  <span>All</span>
                </button>
              </div>
            </div>
          </header>
          <div className="projects__container">
            {data.map((project) => (
              <article
                key={project.id}
                className="project"
                style={{
                  backgroundImage: `url(${project.image.default.src})`,
                }}
              >
                <Link
                  href={`/projectDetail/${project.id}`}
                  className="project__linkContainer"
                >
                  <div className="project__container">
                    <h3 className="project__name">
                      {project.name}
                      <span>_</span>
                    </h3>
                  </div>
                </Link>
              </article>
            ))}
          </div>
          {/* <div className="base__seeMore">
            <a href="">See More</a>
          </div> */}
        </section>
      </div>
    </>
  );
};

export default Projects;
