import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { projects } from "../../data";
// import Swiper core and required modules
import { Navigation, Pagination, Scrollbar, A11y, Autoplay } from "swiper";

import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "swiper/css/autoplay";

import Image from "next/image";
import Head from "next/head";

const ProjectDetail = () => {
  const { query, isReady } = useRouter();
  const [project, setProject] = useState();
  // console.log(query);
  useEffect(() => {
    if (isReady) {
      const project = projects.find((p) => p.id.toString() === query.slug);
      setProject(project);
    }
  }, [isReady]);
  return (
    <>
      {project && (
        <Head>
          <title>{project.name} | Nguyen Vu</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      )}
      {project && (
        <div className="wrapper">
          <section className="projectDetail">
            <h1 className="base__title">{project.name}</h1>
            <div className="projectDetail__container">
              <div className="projectDetail__infoContainer">
                <div className="projectDetail__textContainer">
                  <p className="projectDetail__text">{project.description}</p>
                  <span className="projectDetail__labelContainer">
                    <p className="projectDetail__subTitle">Skills:</p>
                    {project.labels.map((label, index) => (
                      <span key={index} className="projectDetail__label">
                        {label}
                      </span>
                    ))}
                  </span>
                </div>
                <div className="slider">
                  <Swiper
                    // install Swiper modules
                    modules={[
                      Navigation,
                      Pagination,
                      Scrollbar,
                      A11y,
                      Autoplay,
                    ]}
                    spaceBetween={50}
                    slidesPerView={1}
                    navigation
                    pagination={{ clickable: true }}
                    grabCursor
                    loop={true}
                    autoplay={{
                      delay: 1800,
                      disableOnInteraction: true,
                    }}
                  >
                    {project.imagesSlider.map((img, index) => (
                      <SwiperSlide key={index}>
                        <div className="scene" style={{ position: "relative" }}>
                          <Image
                            src={img.image.default.src}
                            alt=""
                            width={720}
                            height={405}
                            priority
                          />
                        </div>
                      </SwiperSlide>
                    ))}
                  </Swiper>
                </div>
              </div>
              <div className="projectDetail__links">
                <a
                  href={project.liveSite}
                  className="margin"
                  target="_blank"
                  rel="noreferrer"
                >
                  Go to Site
                </a>
                <a href={project.liveCode} target="_blank" rel="noreferrer">
                  Code in Github
                </a>
              </div>
            </div>
          </section>
        </div>
      )}
    </>
  );
};

export default ProjectDetail;
